//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WardrobeProject9.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessory
    {
        public int AccessorieID { get; set; }
        public string AccessorieName { get; set; }
        public string AccessoriePhoto { get; set; }
        public string AccessorieColor { get; set; }
        public string AccessorieSeason { get; set; }
        public string AccessorieOccasion { get; set; }
        public string AccessorieType { get; set; }
    }
}
